# syntax=docker/dockerfile:1
FROM golang:1.26.4-alpine AS build
WORKDIR /src
COPY deploy/dockerfiles/go.work.mail-moderation ./go.work
COPY gen/go gen/go
COPY services/license services/license
COPY services/platform services/platform
COPY services/comms/mail-moderation services/comms/mail-moderation
WORKDIR /src/services/comms/mail-moderation
RUN go build -o /out/mail-moderation ./cmd/mail-moderation

FROM alpine:3.20
COPY --from=build /out/mail-moderation /usr/local/bin/era-mail-moderation
EXPOSE 8360 2525
ENTRYPOINT ["/usr/local/bin/era-mail-moderation"]
